// <auto-generated />
using System;
using LicenciaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicenciaBackend.Migrations
{
    [DbContext(typeof(LicenciaDbContext))]
    partial class LicenciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicenciaBackend.Models.LicenciaRegistrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpLocal")
                        .HasColumnType("text");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<int>("MaxDispositivos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsuariosLocales")
                        .HasColumnType("integer");

                    b.Property<string>("Origen")
                        .HasColumnType("text");

                    b.Property<bool>("PermitirRemoto")
                        .HasColumnType("boolean");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("LicenciaBackend.Models.LicenciaRegistrada", b =>
                {
                    b.OwnsOne("LicenciaBackend.Models.LicenciaFirmada", "Firma", b1 =>
                        {
                            b1.Property<int>("LicenciaRegistradaId")
                                .HasColumnType("integer");

                            b1.Property<string>("DatosBase64")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FirmaBase64")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LicenciaRegistradaId");

                            b1.ToTable("Licencias");

                            b1.WithOwner()
                                .HasForeignKey("LicenciaRegistradaId");
                        });

                    b.OwnsOne("LicenciaBackend.Models.LicenciaInfo", "Info", b1 =>
                        {
                            b1.Property<int>("LicenciaRegistradaId")
                                .HasColumnType("integer");

                            b1.Property<bool>("Activa")
                                .HasColumnType("boolean");

                            b1.Property<string>("ApiUrl")
                                .HasColumnType("text");

                            b1.Property<string>("CUIT")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Clave")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DispositivoId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("EstudioNombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxDispositivos")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxUsuariosLocales")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxUsuariosRemotos")
                                .HasColumnType("integer");

                            b1.Property<string>("Modo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Notas")
                                .HasColumnType("text");

                            b1.Property<bool>("PermitirRemoto")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("ValidoDesde")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("ValidoHasta")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("LicenciaRegistradaId");

                            b1.ToTable("Licencias");

                            b1.WithOwner()
                                .HasForeignKey("LicenciaRegistradaId");
                        });

                    b.Navigation("Firma")
                        .IsRequired();

                    b.Navigation("Info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
